#!/bin/bash

# --- Config ---
URL="https://echo-804893961704.europe-west1.run.app"
LOG_FILE="echo_log.csv"
SLEEP_INTERVAL=5

# --- Script Logic ---
echo "timestamp,latency_s,http_status_code,request_successfull" > "$LOG_FILE"
echo "Starting network test... Logging data to ./${LOG_FILE}"

for i in {1..100}
do
    stats=$(curl -s -o /dev/null -w "%{time_total},%{http_code}" \
    -X POST \
    -H "Content-Type: application/json" \
    -d '{"data":"test"}' \
    "$URL")

    if [ $? -eq 0 ]; then
        REQUEST_SUCCESS="true"
    else
        REQUEST_SUCCESS="false"
    fi

    TIMESTAMP=$(date --iso-8601=seconds)

    echo "${TIMESTAMP},${stats},${REQUEST_SUCCESS}" >> "$LOG_FILE"

    sleep "$SLEEP_INTERVAL"
done
